image: illbilly/sfdx #image with sfdx installed



before_script:

#===install dependancies===
          - apt-get install -y jq #used to check test results
          #===login===
          - openssl enc -d -aes-256-cbc -in assets/server.key.enc -out assets/server.key -K $AESKEY #-iv $IVKEY #deencryt server.key
          - export SFDX_DISABLE_ENCRYPTION=true #required to run sfdx force from CI enviorment
          - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY_HUB --jwtkeyfile assets/server.key --username $USERNAME_HUB --setdefaultdevhubusername
          #===setup org===
          - npm run precreateenv
          - npm run push
          #===get test results===
          - sfdx force:apex:test:run -r json > testresults.json
          #===delete scratch ORG===
          #- sfdx force:org:delete -u ciorg -p #(this currently doesn't work due to known issue)
          #===handle test Results===
          - bash assets/checkTestResults.sh

master: #anything commited to master should be deploy to prod
      stage: deploy
      environment: Production
      only:
        - master
      script:
            #===create deployment package===
            - sfdx force:source:convert -d src
            #===auth with target===
            - openssl enc -d -aes-256-cbc -in assets/server.key.enc -out assets/server.key -K $AESKEY -iv $IVKEY #deencryt server.key
            - export SFDX_DISABLE_ENCRYPTION=true
            - sfdx force:auth:jwt:grant -s --clientid $CONSUMERKEY_TARGET --jwtkeyfile assets/server.key --username $USERNAME_TARGET
            #===deploy===
            - sfdx force:mdapi:deploy -d src -w 200 -e true #warning: this doesn't actually throw a build failure

    